@start /b cmd /c grails create-plugin banner-general-proxy
@start /b cmd /c grails create-plugin banner-general-personal-information-ui
@start /b cmd /c grails create-plugin banner-general-direct-deposit-ui
@start /b cmd /c grails create-plugin banner-aip-gate-keeper
@start /b cmd /c grails create-plugin banner-aip-ui
@start /b cmd /c grails create-plugin banner-packaging
@start /b cmd /c grails create-plugin i18n-core
@start /b cmd /c grails create-plugin banner-codenarc
@start /b cmd /c grails create-plugin banner-ui-ss
@start /b cmd /c grails create-plugin banner-core
@start /b cmd /c grails create-plugin constraints
@start /b cmd /c grails create-plugin sghe-aurora
@start /b cmd /c grails create-plugin banner-general-utility
@start /b cmd /c grails create-plugin banner-general-person
@start /b cmd /c grails create-plugin banner-general-validation-common
@start /b cmd /c grails create-plugin banner-seeddata-catalog
@start /b cmd /c grails create-plugin banner-spring-security-cas
@start /b cmd /c grails create-plugin banner-spring-security-saml
@start /b cmd /c grails create-plugin banner-general-common
@start /b cmd /c grails create-plugin banner-general-common-ui-ss
@start /b cmd /c grails create-plugin domain-extension
@start /b cmd /c grails create-plugin web-app-extensibility
@start /b cmd /c grails create-plugin banner-aip
@start /b cmd /c grails create-plugin banner-sspb
@start /b cmd /c grails create-plugin banner-restful-api-support
@start /b cmd /c grails create-plugin restful-api
@start /b cmd /c grails create-plugin banner-document-management
EXIT